# Use the official Python image from Docker Hub
FROM python:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the Python source file into the container
COPY main.py .

# Run the Python script
CMD ["python", "main.py"]
