exports.SkillRequired=[
    {name:"React.js",icon:"+"},
    {name:"Express.js",icon:"+"},
    {name:"Node.js",icon:"+"},
    {name:"MongoDB.js",icon:"+"},
    {name:"Vue.js",icon:"+"},
    {name:"Next.js",icon:"+"},
    {name:"Blockchain.js",icon:"+"},
]